// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWKza9gk7ZsQkpteCKBUJjZ9W3xGhKwEw',
    appId: '1:577727682419:web:843cbb8834bfddca5a1706',
    messagingSenderId: '577727682419',
    projectId: 'flutter-machine-test-b422a',
    authDomain: 'flutter-machine-test-b422a.firebaseapp.com',
    storageBucket: 'flutter-machine-test-b422a.appspot.com',
    measurementId: 'G-WVYMK1DTFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAqgxrWmlquhrMJN3U2Ij4qqOGU3b8p6s',
    appId: '1:577727682419:android:a204d01e4a5b38e95a1706',
    messagingSenderId: '577727682419',
    projectId: 'flutter-machine-test-b422a',
    storageBucket: 'flutter-machine-test-b422a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ii32n9B_PLh33KIU-mrfsqwDA6nNStU',
    appId: '1:577727682419:ios:35a46c3ee386082b5a1706',
    messagingSenderId: '577727682419',
    projectId: 'flutter-machine-test-b422a',
    storageBucket: 'flutter-machine-test-b422a.appspot.com',
    iosBundleId: 'com.example.flutterMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ii32n9B_PLh33KIU-mrfsqwDA6nNStU',
    appId: '1:577727682419:ios:35a46c3ee386082b5a1706',
    messagingSenderId: '577727682419',
    projectId: 'flutter-machine-test-b422a',
    storageBucket: 'flutter-machine-test-b422a.appspot.com',
    iosBundleId: 'com.example.flutterMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWKza9gk7ZsQkpteCKBUJjZ9W3xGhKwEw',
    appId: '1:577727682419:web:40ef9012d3cda3a85a1706',
    messagingSenderId: '577727682419',
    projectId: 'flutter-machine-test-b422a',
    authDomain: 'flutter-machine-test-b422a.firebaseapp.com',
    storageBucket: 'flutter-machine-test-b422a.appspot.com',
    measurementId: 'G-0V3RFPPB75',
  );
}
